// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using OrderData.Models;

namespace OrderData.Models
{
    public partial class ApiHeroLimited
    {
        private string _color;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Color
        {
            get { return this._color; }
            set { this._color = value; }
        }
        
        private double? _debitPrice;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? DebitPrice
        {
            get { return this._debitPrice; }
            set { this._debitPrice = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _imageUrl;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ImageUrl
        {
            get { return this._imageUrl; }
            set { this._imageUrl = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private double? _rating;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Rating
        {
            get { return this._rating; }
            set { this._rating = value; }
        }
        
        private double? _ratingCount;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? RatingCount
        {
            get { return this._ratingCount; }
            set { this._ratingCount = value; }
        }
        
        private IList<ApiHeroSkill> _skills;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ApiHeroSkill> Skills
        {
            get { return this._skills; }
            set { this._skills = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ApiHeroLimited class.
        /// </summary>
        public ApiHeroLimited()
        {
            this.Skills = new LazyList<ApiHeroSkill>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken colorValue = inputObject["Color"];
                if (colorValue != null && colorValue.Type != JTokenType.Null)
                {
                    this.Color = ((string)colorValue);
                }
                JToken debitPriceValue = inputObject["DebitPrice"];
                if (debitPriceValue != null && debitPriceValue.Type != JTokenType.Null)
                {
                    this.DebitPrice = ((double)debitPriceValue);
                }
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken imageUrlValue = inputObject["ImageUrl"];
                if (imageUrlValue != null && imageUrlValue.Type != JTokenType.Null)
                {
                    this.ImageUrl = ((string)imageUrlValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken ratingValue = inputObject["Rating"];
                if (ratingValue != null && ratingValue.Type != JTokenType.Null)
                {
                    this.Rating = ((double)ratingValue);
                }
                JToken ratingCountValue = inputObject["RatingCount"];
                if (ratingCountValue != null && ratingCountValue.Type != JTokenType.Null)
                {
                    this.RatingCount = ((double)ratingCountValue);
                }
                JToken skillsSequence = ((JToken)inputObject["Skills"]);
                if (skillsSequence != null && skillsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken skillsValue in ((JArray)skillsSequence))
                    {
                        ApiHeroSkill apiHeroSkill = new ApiHeroSkill();
                        apiHeroSkill.DeserializeJson(skillsValue);
                        this.Skills.Add(apiHeroSkill);
                    }
                }
            }
        }
    }
}
