// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace OrderData.Models
{
    public partial class ApiHeroSearch
    {
        private DateTimeOffset? _endTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? EndTime
        {
            get { return this._endTime; }
            set { this._endTime = value; }
        }
        
        private DateTimeOffset? _startTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? StartTime
        {
            get { return this._startTime; }
            set { this._startTime = value; }
        }
        
        private string _text;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Text
        {
            get { return this._text; }
            set { this._text = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ApiHeroSearch class.
        /// </summary>
        public ApiHeroSearch()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ApiHeroSearch
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.EndTime != null)
            {
                outputObject["EndTime"] = this.EndTime.Value;
            }
            if (this.StartTime != null)
            {
                outputObject["StartTime"] = this.StartTime.Value;
            }
            if (this.Text != null)
            {
                outputObject["Text"] = this.Text;
            }
            return outputObject;
        }
    }
}
