// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using OrderData.Models;

namespace OrderData.Models
{
    public static partial class ApiSkillCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ApiSkill> DeserializeJson(JToken inputObject)
        {
            IList<ApiSkill> deserializedObject = new List<ApiSkill>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ApiSkill apiSkill = new ApiSkill();
                apiSkill.DeserializeJson(iListValue);
                deserializedObject.Add(apiSkill);
            }
            return deserializedObject;
        }
    }
}
