// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using OrderData.Models;

namespace OrderData.Models
{
    public static partial class DbBookingCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<DbBooking> DeserializeJson(JToken inputObject)
        {
            IList<DbBooking> deserializedObject = new List<DbBooking>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                DbBooking dbBooking = new DbBooking();
                dbBooking.DeserializeJson(iListValue);
                deserializedObject.Add(dbBooking);
            }
            return deserializedObject;
        }
    }
}
