// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using OrderData.Models;

namespace OrderData.Models
{
    public partial class DbSkill
    {
        private IList<DbBooking> _bookings;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<DbBooking> Bookings
        {
            get { return this._bookings; }
            set { this._bookings = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _keywords;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Keywords
        {
            get { return this._keywords; }
            set { this._keywords = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DbSkill class.
        /// </summary>
        public DbSkill()
        {
            this.Bookings = new LazyList<DbBooking>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken bookingsSequence = ((JToken)inputObject["Bookings"]);
                if (bookingsSequence != null && bookingsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken bookingsValue in ((JArray)bookingsSequence))
                    {
                        DbBooking dbBooking = new DbBooking();
                        dbBooking.DeserializeJson(bookingsValue);
                        this.Bookings.Add(dbBooking);
                    }
                }
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken keywordsValue = inputObject["Keywords"];
                if (keywordsValue != null && keywordsValue.Type != JTokenType.Null)
                {
                    this.Keywords = ((string)keywordsValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type DbSkill
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray bookingsSequence = null;
            if (this.Bookings != null)
            {
                if (this.Bookings is ILazyCollection<DbBooking> == false || ((ILazyCollection<DbBooking>)this.Bookings).IsInitialized)
                {
                    bookingsSequence = new JArray();
                    outputObject["Bookings"] = bookingsSequence;
                    foreach (DbBooking bookingsItem in this.Bookings)
                    {
                        if (bookingsItem != null)
                        {
                            bookingsSequence.Add(bookingsItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.Description != null)
            {
                outputObject["Description"] = this.Description;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id.Value;
            }
            if (this.Keywords != null)
            {
                outputObject["Keywords"] = this.Keywords;
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            return outputObject;
        }
    }
}
