// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using OrderData;
using OrderData.Models;

namespace OrderData
{
    public static partial class HeroesExtensions
    {
        /// <param name='operations'>
        /// Reference to the OrderData.IHeroes.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static ApiHeroLimited GetHero(this IHeroes operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IHeroes)s).GetHeroAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the OrderData.IHeroes.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ApiHeroLimited> GetHeroAsync(this IHeroes operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<OrderData.Models.ApiHeroLimited> result = await operations.GetHeroWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the OrderData.IHeroes.
        /// </param>
        public static IList<ApiHeroLimited> GetHeroes(this IHeroes operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IHeroes)s).GetHeroesAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the OrderData.IHeroes.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<ApiHeroLimited>> GetHeroesAsync(this IHeroes operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<OrderData.Models.ApiHeroLimited>> result = await operations.GetHeroesWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the OrderData.IHeroes.
        /// </param>
        /// <param name='search'>
        /// Required.
        /// </param>
        public static IList<ApiHeroLimited> PostHeroes(this IHeroes operations, ApiHeroSearch search)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IHeroes)s).PostHeroesAsync(search);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the OrderData.IHeroes.
        /// </param>
        /// <param name='search'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<ApiHeroLimited>> PostHeroesAsync(this IHeroes operations, ApiHeroSearch search, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<OrderData.Models.ApiHeroLimited>> result = await operations.PostHeroesWithOperationResponseAsync(search, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
